apiVersion: v1
kind: Secret
metadata:
  name: proxy-rfc2217-secrets
  namespace: waterius
type: Opaque
stringData:
  # Generate random token: openssl rand -hex 16
  auth-token: "YOUR_AUTH_TOKEN"
  web-user: "admin"
  # Generate random password: openssl rand -base64 24
  web-pass: "YOUR_WEB_PASSWORD"
