apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: regcred
  namespace: waterius
data:
  # Generate with: kubectl create secret docker-registry regcred --docker-server=YOUR_REGISTRY --docker-username=YOUR_USER --docker-password=YOUR_PASSWORD --docker-email=YOUR_EMAIL --dry-run=client -o yaml
  .dockerconfigjson: YOUR_BASE64_ENCODED_DOCKER_CONFIG
