# ClusterIP сервис для внутреннего доступа (API, ingress)
apiVersion: v1
kind: Service
metadata:
  name: proxy-rfc2217
  namespace: waterius
  labels:
    app: proxy-rfc2217
spec:
  type: ClusterIP
  selector:
    app: proxy-rfc2217
  ports:
    - name: api
      port: 8080
      targetPort: 8080
      protocol: TCP
---
# LoadBalancer сервис для TCP с сохранением реальных IP
apiVersion: v1
kind: Service
metadata:
  name: proxy-rfc2217-tcp
  namespace: waterius
  labels:
    app: proxy-rfc2217
spec:
  type: LoadBalancer
  loadBalancerIP: 10.9.3.17
  externalTrafficPolicy: Local
  selector:
    app: proxy-rfc2217
  ports:
    - name: tcp
      port: 2217
      targetPort: 2217
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: proxy-rfc2217
  namespace: waterius
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - rfc2217.pstd.ru
      secretName: rfc2217-tls
  rules:
    - host: rfc2217.pstd.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy-rfc2217
                port:
                  number: 8080
